# Generated by Django 5.2.3 on 2025-06-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_annnouncement_alter_event_slug_announcementimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annnouncement',
            new_name='Announcement',
        ),
    ]
