# Generated by Django 5.2.3 on 2025-06-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_rename_annnouncement_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='keywords',
            field=models.CharField(blank=True, default='announcement', max_length=50, null=True),
        ),
    ]
