# Generated by Django 5.2.3 on 2025-06-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_announcement_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='location',
            field=models.CharField(blank=True, default='Joshimath', max_length=200, null=True),
        ),
    ]
