# Generated by Django 5.2.3 on 2025-07-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_contact_stotracategory_stotra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carausel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carasoul_images/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
