# Generated by Django 5.2.3 on 2025-09-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_carausel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
