# Generated by Django 5.2.3 on 2025-09-25 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_branches'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branches',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='branches',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
