# Generated by Django 5.2.3 on 2025-09-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_puja_priest_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
