# Generated by Django 5.2.3 on 2025-09-26 06:35

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region=None),
        ),
    ]
