# Generated by Django 5.2.3 on 2025-09-26 06:38

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_alter_booking_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region='IN'),
        ),
    ]
