# Generated by Django 5.2.3 on 2025-09-27 04:38

import phonenumber_field.modelfields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_booking_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Epass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('date_of_visit', models.DateField()),
                ('contact_number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region='IN')),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.TextField()),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
            ],
        ),
    ]
