# Generated by Django 5.2.3 on 2025-09-28 04:08

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0016_epass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epass',
            name='id',
            field=models.PositiveIntegerField(default=Home.models.generate_pass_id, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
